title: taco.moe
description: "Technical blog of Ryan Miller. This site has nothing to do with tacos, sorry!"
author:
  name: "Ryan Miller"
  email: "miller@redhat.com"
  url: "https://https://ryanmillerc.github.io"

url: "https://https://ryanmillerc.github.io"
baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
favmoji: "🌮"
header_title: "ryanmillerc@github.com:~ $"
name: "Ryan's Blog"
owner: "Ryan Miller"
year: "2022"

github_url: "https://github.com/RyanMillerC"
linkedin_url: "http://www.linkedin.com/in/millerryanc"
